services:
  db-abnt:
    image: postgres:17-alpine
    container_name: postgres_abnt_container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: abnt_db
    ports:
      - "5432:5432"
    volumes:
      - abnt_data:/var/lib/postgresql/data
    networks:
      - abnt-network

volumes:
  abnt_data:

networks:
  abnt-network:
    driver: bridge